swagger: '2.0'
info:
  version: '1.0'
  title: "QEdu API"
  description: Acesso aos dados públicos da Educação Básica brasileira.
  license:
    name: MIT
    url: https://github.com/apiaryio/polls-api/blob/master/LICENSE
host: polls.apiblueprint.org
basePath: /
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /ideb:
    x-summary: Índice de Desenvolvimento da Educação Básica
    get:
      summary: Dados do Brasil, Estados, Municípios
      description: Retorna os dados do IDEB para Brasil, Estados e Municípios através do Código do IBGE.
      parameters:
        - in: query
          name: ibge_id
          type: integer
          required: true
          description: 'Código IBGE dos estados e municípios, para dados do Brasil informar o Código 7'
        - in: query
          name: ano
          type: integer
          required: true
          description: 'Ano do resultado do IDEB'
        - in: query
          name: dependencia_id
          type: integer
          required: false
          description: 'Código da Dependência Administrativa'
      responses:
        200:
          description: Sucesso
          schema:
            type: array
            items:
              $ref: '#/definitions/Ideb'
          examples:
            application/json:
              data:
                - 
                  id: 17
                  dependencia_id: 2
                  ciclo_id: AI
                  ano: 2019
                  ideb: 5.8
                  ideb_crescimento: 1.0
                  aprendizado: 6.1977
                  nota_mt: 229.54
                  nota_lp: 211.61
                  ideb_projetado: 5.6
                  ideb_aumentou: 0
                  aprovacao: 92.6
definitions:
  Ideb:
    title: IDEB
    type: object
    properties:
      id:
        type: integer
        description: ID do código IBGE para resultados de BR, Estados ou Municípios e INEP no caso de busca por escolas.
      dependencia_id:
        type: integer
        description: Código de Dependência Administrativa (1 - Federal, 2 - Estadual, 3 - Municipal, 4 - Privada, 5 - Pública)
      ciclo_id:
        type: string
        description: Identifica a etapa de ensino
      ano:
        type: integer
        description: Ano que foi realizado a avaliação
      ideb:
        type: number
        description: Resultado do IDEB
      ideb_crescimento:
        type: number
        description: Quanto o IDEB cresceu desde a última avaliação
      aprendizado:
        type: number
        description: Nota do aprendizado. Valor de 0 a 10.
      nota_mt:
        type: number
        description: Nota do aprendizado em matemática.
      nota_lp:
        type: number
        description: Nota do aprendizado em lingua portuguesa.
      ideb_projetado:
        type: number
        description: Nota projetada para o IDEB.
      ideb_aumentou:
        type: boolean
        description: 'Valida se o IDEB teve aumento em relação a edição anterior.'
      aprovacao:
        type: number
        description: 'Taxa de aprovação'
        
securityDefinitions:
  Authorization:
    type: apiKey
    in: header
    name: Authorization
security:
  - Authorization: ["Bearer token123"]